### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by ghost** [ShinyDialga45/Forecast#1]
(removed)

**Comment by twizmwazin** [comment]
@TiTo-418 This is a library, not a plugin. It does nothing by itself.

**Comment by TiTo-418** [comment]
a library like sportbukkit?

**Comment by ShinyDialga** [comment]
You use this as an API in your plugins so you don't have to code it yourself. For example, if you want to get all the members of your team so that you can broadcast them in chat, you can use this.

**Comment by ghost** [comment]
Yeah, sorry
